language: c

script: ./travis-tool.sh run_tests

after_failure:
- ./travis-tool.sh dump_logs

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo apt-get update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
  - ./travis-tool.sh install_aptget gdal-bin
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install ggplot2 maps RColorBrewer
  - ./travis-tool.sh install_github jimhester/covr

install:
  - ./travis-tool.sh install_deps

env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS="--as-cran"
  - BOOTSTRAP_LATEX="1"

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=
