language: r
dist: trusty
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - protobuf-compiler
  - valgrind

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:jeroen/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin libv8-dev libjq-dev

after_success:
  - Rscript -e 'covr::codecov()'

compiler:
  - clang

warnings_are_errors: false

r_packages:
  - colorspace
  - gistr

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=

